version: '3.9'

services:
  digital-shop-app:
    build:
      context: .
    command: >
      sh -c "
        python manage.py wait_for_db &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        gunicorn digitalshopapp.wsgi --bind 0.0.0.0:8000
      "
    volumes:
      - ./digital-shop-app:/digital-shop-app
      - ./data/web:/vol/web
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    command: >
      sh -c "npm run dev"
    volumes:
      - ./frontend/react:/react
      - react_build:/react/assets/ready-build
    env_file: .env

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - digital-shop-app
      - frontend

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

volumes:
  react_build: