# This Dockerfile is used only for test service in docker-compose
FROM python:3.9-alpine3.13

ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt /requirements.txt
COPY ./digital-shop-app /digital-shop-app

WORKDIR /digital-shop-app

RUN python -m venv /py && \
    /py/bin/pip install --upgrade pip && \
    apk add --no-cache bash curl gnupg coreutils && \
    apk add --update --no-cache postgresql-client libjpeg && \
    apk add --update --no-cache --virtual .tmp-deps \
        build-base jpeg-dev postgresql-dev musl-dev linux-headers \
        zlib-dev libffi-dev openssl-dev python3-dev cargo && \
    /py/bin/pip install -r /requirements.txt && \
    apk del .tmp-deps && \
    adduser --disabled-password --no-create-home testuser && \
    chown -R testuser:testuser /py/lib/python3.9/site-packages && \
    chmod -R +x /scripts && \
    # Coverage directory
    mkdir -p /digital-shop-app/cov && \
    chown -R testuser:testuser /digital-shop-app/cov

USER testuser

ENV PATH="/py/bin:/py/lib:$PATH"