# Generated by Django 3.2.12 on 2022-03-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='creation_date',
            field=models.DateTimeField(verbose_name='Creation date'),
        ),
    ]
