# Generated by Django 3.2.12 on 2022-03-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_cart_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_seller',
            field=models.BooleanField(default=False, editable=False, verbose_name='Seller'),
        ),
    ]
