# Generated by Django 3.2.11 on 2022-01-21 19:14

import django.core.validators
from django.db import migrations, models
import mainapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.FileField(blank=True, error_messages={'invalid_extension': 'This format does not supported.'}, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'png')), mainapp.validators.validate_file_size], verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, error_messages={'invalid_extension': 'This format does not supported.'}, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'png')), mainapp.validators.validate_file_size], verbose_name='Image'),
        ),
    ]
