# Generated by Django 3.2.11 on 2022-02-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20220206_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=600, verbose_name='Description'),
        ),
    ]
