FROM nginxinc/nginx-unprivileged:1-alpine
LABEL maintainer="lomank200222@gmail.com"

COPY ./run.sh /run.sh

USER root

RUN touch /etc/nginx/conf.d/default.conf && \
    chown nginx:nginx /etc/nginx/conf.d && \
    chmod +x /run.sh && \
    mkdir -p /var/www/react/ && \
    mkdir -p /var/www/django/

COPY ./config/default-deploy.conf /etc/nginx/conf.d/default.conf
COPY ./ready-build/* /var/www/react/

USER nginx

CMD ["/run.sh"]
