name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linter
        run: |
          cat .env.sample >> .env
          docker-compose up --exit-code-from lint lint
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          cat .env.sample >> .env
          docker-compose up --exit-code-from test test
          curl -Os https://uploader.codecov.io/latest/alpine/codecov
          chmod +x codecov
          ./codecov
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
