name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linter
        run: |
          cat .env.sample >> .env
          docker-compose up --exit-code-from lint lint
  
  test:
    runs-on: ubuntu-latest
    steps:
      - run: adduser --disabled-password --no-create-home digitalshop
      - run: chown -R digitalshop:digitalshop /digital-shop-app
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          cat .env.sample >> .env
          docker-compose up --exit-code-from test test
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
