name: CI

on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linter
        run: |
          cat .env.sample >> .env
          docker-compose up --exit-code-from lint lint
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          cat .env.sample >> .env
          docker-compose up --exit-code-from test test
